name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Configure gcloud project
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set run/region ${{ env.REGION }}

      - name: Configure Docker to use gcloud credential helper
        run: gcloud auth configure-docker --quiet

      - name: Set image name
        run: echo "IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          build-args: |
            VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }}
            VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }}
            VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }}
            VITE_CLIENT_SECRET=${{ secrets.VITE_CLIENT_SECRET }}
            VITE_FORGOT_PASSWORD_URL=${{ secrets.VITE_FORGOT_PASSWORD_URL }}
            VITE_PROFILEAPI_URL=${{ secrets.VITE_PROFILEAPI_URL }}
            VITE_BACKEND_BASE_URL=${{ secrets.VITE_BACKEND_BASE_URL }}
            VITE_ADDRESSY_API_KEY=${{ secrets.VITE_ADDRESSY_API_KEY }}
            VITE_ADDRESSY_BASE_URL=${{ secrets.VITE_ADDRESSY_BASE_URL }}

      - name: Deploy to Cloud Run (using built image)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          flags: --allow-unauthenticated

      - name: Show deployment URL
        run: |
          echo "Deployment URL: ${{ steps.deploy.outputs.url }}"
